### ISSUE TITLE
请问为何使用fisp部署此demo，访问时会报错？

### ISSUE THREAD

**Issue by jnduan** [fouber/fis-java-jsp#1]
使用

```
fis release -cw
fis server start
```

是可以正常访问的，但是如果使用

```
fisp release -cw
fisp server start
```

则会出现OOM：

```
java.lang.StackOverflowError
    at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.setAttribute(Dispatcher.java:523)
    at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.setAttribute(Dispatcher.java:523)
    at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.setAttribute(Dispatcher.java:523)
    at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.setAttribute(Dispatcher.java:523)
......
```

google了一下，貌似jetty出现这种异常是因为jsp:include没有找到文件，把index.jsp中include语句拿掉，也确实不再报错。

当然，也许这个issue写在这里不太合适，但是好像fisp没开源的样子，fis-dev下的fis-pc就是fisp么？

**Comment by fouber** [comment]
fisp 是面向smarty的，内置的插件都是与php、smarty相关，这里的demo是java-jsp的，请使用fis来运行
